  version: '3'
  services:
      app:
         build: .
         container_name : app
         volumes:
            - .:/var/www
         entrypoint: dockerize -template ./.docker/app/envtemplate:.env -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
         networks:
            - app-network
         depends_on:
            - db
            - redis
         environment:
            - DB_HOST=db
            - DB_DATABASE=laravel
            - DB_USERNAME=root
            - DB_PASSWORD=root




      db:
         image: mysql:5.7
         command: --innodb-use-native-aio=0
         container_name: db
         restart: always
         tty: true
         ports: 
            - "33006:3306"
         volumes:
            - ./dbdata:/var/lib/mysql
         environment: 
            - MYSQL_DATABASE=laravel
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
         networks:
            - app-network

      nginx:
        build: ./.docker/nginx
        container_name : nginx
        environment: 
            - TEST_HOST=app
            - TEST_PORT=9000
        restart : always
        tty : true
        ports : 
           - "8000:80"
        volumes:
           - .:/var/www
        entrypoint: dockerize -template /var/www/.docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf nginx -g "daemon off";
        depends_on:
           - app
        networks:
           - app-network
      redis:
        image: redis:alpine
        expose: 
           - 6379
  networks:
     app-network: 
        driver: bridge